import { afterEach, describe, expect, test } from "bun:test"
import { appendFile, mkdtemp, readFile, rm, utimes, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { buildExtension, checkExtensionCurrent } from "./build-extension.mjs"

const scriptDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(scriptDir, "..", "..", "..", "..")
const tempRoots = []

afterEach(async () => {
  await Promise.all(tempRoots.splice(0).map((root) => rm(root, { recursive: true, force: true })))
})

async function builtOutputs() {
  const root = await mkdtemp(join(repoRoot, ".build-extension-test-"))
  tempRoots.push(root)
  const outputPath = join(root, "omo.js")
  const memberOutputPath = join(root, "omo-member.js")
  const build = await buildExtension({ outputPath, memberOutputPath })
  return { outputPath, memberOutputPath, ...build }
}

describe("checkExtensionCurrent", () => {
  test("#given current generated outputs with old mtimes #when checked #then freshness passes", async () => {
    // given
    const outputs = await builtOutputs()
    const old = new Date(0)
    await Promise.all([utimes(outputs.outputPath, old, old), utimes(outputs.memberOutputPath, old, old)])

    // when
    const result = await checkExtensionCurrent(outputs)

    // then
    expect(result).toMatchObject({ ok: true })
  })

  test("#given changed generated bytes with future mtimes #when checked #then freshness fails", async () => {
    // given
    const outputs = await builtOutputs()
    await appendFile(outputs.outputPath, "\nchanged\n")
    const future = new Date("2100-01-01T00:00:00.000Z")
    await utimes(outputs.outputPath, future, future)

    // when
    const result = await checkExtensionCurrent(outputs)

    // then
    expect(result).toMatchObject({ ok: false, reason: "stale-output", output: outputs.outputPath })
  })

  test("#given intact generated bytes with a stale source digest #when checked #then source reproduction fails", async () => {
    // given
    const outputs = await builtOutputs()
    const artifact = await readFile(outputs.outputPath, "utf8")
    const newline = artifact.indexOf("\n")
    const [prefix, , bodyDigest] = artifact.slice(0, newline).split(":")
    await writeFile(outputs.outputPath, `${prefix}:${"0".repeat(64)}:${bodyDigest}\n${artifact.slice(newline + 1)}`)

    // when
    const result = await checkExtensionCurrent(outputs)

    // then
    expect(result).toMatchObject({ ok: false, reason: "stale-output", output: outputs.outputPath })
  })

  test("#given freshly built outputs #when inspected #then normalization removes whitespace-only lines", async () => {
    // given
    const outputs = await builtOutputs()

    // when
    const main = await readFile(outputs.outputPath, "utf8")
    const member = await readFile(outputs.memberOutputPath, "utf8")

    // then
    expect(main).not.toMatch(/^[\t ]+$/m)
    expect(member).not.toMatch(/^[\t ]+$/m)
  })

  test("#given the main extension build #when its metafile inputs are inspected #then senpi-task implementation sources are included", async () => {
    // given / when
    const inputs = (await builtOutputs()).mainInputs

    // then
    expect(inputs.some((input) => input.endsWith("packages/senpi-task/src/runners/in-process/curated-readonly-bash.ts"))).toBe(true)
  })
})
