// Shared memory tool identity + description metadata. The senpi ToolDefinition layer (tools.ts) and the
// standalone MCP server (src/mcp/memory-server.ts) both consume this module, so it must stay free of
// TypeBox and harness imports: the MCP bundle runs under plain Node with no senpi runtime present.

export const MEMORY_TOOL_NAME = "memory"
export const MEMORY_APPLY_PATCH_TOOL_NAME = "memory_apply_patch"

export const MEMORY_TOOL_DESCRIPTION = [
  "A convenience tool for memories stored in the omo memory repo that automatically commits changes. The harness syncs clean committed memory changes after the turn.",
  "",
  "Memory files are markdown documents with YAML frontmatter. Frontmatter carries a `description` (required on create; it is what the memory index shows) and may set `read_only: \"true\"` to block modification. Edits preserve existing frontmatter.",
  "",
  "Supported operations on memory files:",
  "- `str_replace`",
  "- `insert`",
  "- `delete` (files, or directories recursively)",
  "- `rename` (path rename only)",
  "- `update_description`",
  "- `create`",
  "For larger reorganizations, use memory_apply_patch instead.",
  "",
  "Path formats accepted:",
  "- relative memory file paths (e.g. `system/contacts.md`, `reference/project/team.md`)",
  "- absolute paths only when they are inside the memory repo",
  "",
  "Note: absolute paths outside the memory repo are rejected.",
  "",
  "When creating or deleting files, check for `[[path]]` references in other memory files that may need to be added or updated. Keeping references consistent ensures future discoverability.",
  "",
  "On success the tool returns `Memory <command> committed locally (<sha>).`, or `Memory <command> committed (<sha>); harness will sync after the turn.` when a remote is configured. Commits are authored with the bound omo memory identity.",
  "",
  "Examples:",
  "",
  "```python",
  '# Replace text in a memory file',
  'memory(command="str_replace", reason="Update theme preference", file_path="system/human/preferences.md", old_string="theme: dark", new_string="theme: light")',
  "",
  "# Insert text at line 5",
  'memory(command="insert", reason="Add note about meeting", file_path="reference/history/meeting-notes.md", insert_line=5, insert_text="New note here")',
  "",
  "# Delete a memory file",
  'memory(command="delete", reason="Remove stale notes", file_path="reference/history/old_notes.md")',
  "",
  "# Rename a memory file",
  'memory(command="rename", reason="Promote temp notes", old_path="reference/history/temp.md", new_path="reference/history/permanent.md")',
  "",
  "# Update a block description",
  'memory(command="update_description", reason="Clarify coding prefs block", file_path="system/human/prefs/coding.md", description="The user\'s coding preferences.")',
  "",
  "# Create a block with starting text",
  'memory(command="create", reason="Track coding preferences", file_path="system/human/prefs/coding.md", description="The user\'s coding preferences.", file_text="The user adds type hints to all of their Python code.")',
  "```",
].join("\n")

export const MEMORY_APPLY_PATCH_DESCRIPTION = [
  "Apply a codex-style patch to memory files in the omo memory repo, then automatically commit the change. The harness syncs clean committed memory changes after the turn.",
  "",
  "This is similar to `apply_patch`, but scoped to the memory repo and with memory-aware guardrails.",
  "",
  "- Required args:",
  "  - `reason` — git commit message for the memory change",
  "  - `input` — patch text using the standard apply_patch format",
  "",
  "Patch format:",
  "- `*** Begin Patch`",
  "- `*** Add File: <path>`",
  "- `*** Update File: <path>`",
  "  - optional `*** Move to: <path>`",
  "  - one or more `@@` hunks with ` `, `-`, `+` lines",
  "- `*** Delete File: <path>`",
  "- `*** End Patch`",
  "",
  "Path rules:",
  "- Relative paths are interpreted inside the memory repo",
  "- Absolute paths are allowed only when under the memory repo",
  "- Paths outside the memory repo are rejected",
  "",
  "Memory rules:",
  "- Operates on markdown memory files (`.md`) with YAML frontmatter",
  "- Updated/deleted files must be valid memory files with frontmatter",
  "- `read_only: \"true\"` files cannot be modified",
  "- If adding a file without frontmatter, frontmatter is created automatically",
  "",
  "Git behavior:",
  "- Stages changed memory paths",
  "- Commits with `reason`, authored by the bound omo memory identity (`<identity>@omo.local`)",
  "- Sync to a configured remote is handled by the harness after the turn",
  "",
  "On success the tool returns `memory_apply_patch committed locally (<sha>).`, or `memory_apply_patch committed (<sha>); harness will sync after the turn.` when a remote is configured.",
  "",
  "Example:",
  "```python",
  "memory_apply_patch(",
  '  reason="Refine coding preferences",',
  '  input="""*** Begin Patch',
  "*** Update File: system/human/prefs/coding.md",
  "@@",
  "-Use broad abstractions",
  "+Prefer small focused helpers",
  '*** End Patch"""',
  ")",
  "```",
].join("\n")
